Title: Math Apocalypse
Alternate Titles: null
Library: arcade
Series: null
Developer: Esteban Gallardo
Publisher: ""
Play Mode: Single Player
Release Date: null
Version: v1
Languages: en
Extreme: No
Tags: ""
Tag Categories: ""
Source: null
Platform: Flash
Status: Not Working
Application Path: FPSoftware\Flash\flashplayer_32_sa.exe
Launch Command: null
Game Notes: >-
  Math Apocalypse is a mathematical game that was developed by Esteban Gallardo

  [23–25]. It is suited for students within the age of 13 and below. This game was

  designed to help students develop their multiplication, addition, subtraction and division skills. The idea was to use their mathematical skills to fight off an alien invasion by

  solving the presented problems. It was developed as an online game as well as an

  android application. In order to play it online, a user would require Adobe flash player.

  Users are given the opportunity to select the level of difficulty which ranges from 1 to 9

  with 1 being the least difficult and 9 being the most difficult.
Original Description: Math Apocalypse - Use your brain power to fight the alien
  invasion. The earth has been invaded by aliens who feed from the human brain
  activity leaving unconscious the people. You are the last hope to resist the
  invasion. You will have to use your mind power to defeat them
Curation Notes: null
Additional Applications: {}
